$ErrorActionPreference = "Stop"

Write-Host "Installing Cloudflare Wrangler..."
npm install

Write-Host "Opening Cloudflare login..."
npx wrangler login

Write-Host "Deploying Worker..."
$deployOutput = npm run deploy 2>&1 | Tee-Object -Variable deployLines
$deployOutput | Write-Host

$workerUrl = ($deployLines | Select-String -Pattern 'https://[^\s]+\.workers\.dev' |
    Select-Object -Last 1).Matches.Value

if (-not $workerUrl) {
    Write-Warning "Deployment completed, but the Worker URL could not be detected automatically."
    Write-Host "Copy the workers.dev URL into docs\assets\vacation-api-config.js"
    exit 0
}

$configPath = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\docs\assets\vacation-api-config.js"))
$config = @"
/* Generated by cloudflare-worker/deploy.ps1 */
window.VACA_API_BASE = "$workerUrl";
"@
Set-Content -Path $configPath -Value $config -Encoding UTF8

Write-Host ""
Write-Host "Worker deployed: $workerUrl"
Write-Host "Updated: $configPath"
Write-Host "Return to the repository root and run: python -m mkdocs build --strict"
