const ALLOWED_PARKS=new Set(["6","7","8","64","65","334"]);
const ALLOWED_ORIGINS=new Set(["https://caspears.github.io","http://127.0.0.1:8000","http://localhost:8000"]);
const ORLANDO={latitude:28.5383,longitude:-81.3792,timezone:"America/New_York"};
function cors(r){const o=r.headers.get("Origin")||"";return{"Access-Control-Allow-Origin":ALLOWED_ORIGINS.has(o)?o:"https://caspears.github.io","Access-Control-Allow-Methods":"GET,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Access-Control-Max-Age":"86400","Vary":"Origin"}}
function json(r,b,s=200,age=300){return new Response(JSON.stringify(b),{status:s,headers:{...cors(r),"Content-Type":"application/json; charset=utf-8","Cache-Control":`public, max-age=${age}, s-maxage=${age}`}})}
async function getJson(u,i={}){const r=await fetch(u,i);if(!r.ok)throw Error(`${u} returned HTTP ${r.status}`);return r.json()}
async function weather(date){const p=new URLSearchParams({latitude:String(ORLANDO.latitude),longitude:String(ORLANDO.longitude),timezone:ORLANDO.timezone,forecast_days:"16",temperature_unit:"fahrenheit",precipitation_unit:"inch",daily:"weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max",hourly:"temperature_2m,apparent_temperature,weather_code,precipitation_probability,precipitation",current:"temperature_2m,apparent_temperature,weather_code,precipitation"}),d=await getJson(`https://api.open-meteo.com/v1/forecast?${p}`),di=(d.daily?.time||[]).findIndex(x=>x===date),h=[];(d.hourly?.time||[]).forEach((t,i)=>{if(t.startsWith(date))h.push({time:t,temperatureF:d.hourly.temperature_2m?.[i]??null,apparentTemperatureF:d.hourly.apparent_temperature?.[i]??null,weatherCode:d.hourly.weather_code?.[i]??null,precipitationProbability:d.hourly.precipitation_probability?.[i]??null,precipitationInches:d.hourly.precipitation?.[i]??null})});return{date,daily:di>=0?{weatherCode:d.daily.weather_code?.[di]??null,highF:d.daily.temperature_2m_max?.[di]??null,lowF:d.daily.temperature_2m_min?.[di]??null,precipitationProbability:d.daily.precipitation_probability_max?.[di]??null}:null,hourly:h,current:d.current||null}}
async function park(id){const d=await getJson(`https://queue-times.com/parks/${id}/queue_times.json`,{cf:{cacheEverything:true,cacheTtl:300}}),rides=[];for(const l of d.lands||[])for(const r of l.rides||[])rides.push({id:r.id,name:r.name,isOpen:!!r.is_open,waitMinutes:+(r.wait_time||0),lastUpdated:r.last_updated||null,land:l.name||null,queueTimesUrl:`https://queue-times.com/en-US/parks/${id}/rides/${r.id}`});for(const r of d.rides||[])rides.push({id:r.id,name:r.name,isOpen:!!r.is_open,waitMinutes:+(r.wait_time||0),lastUpdated:r.last_updated||null,land:null,queueTimesUrl:`https://queue-times.com/en-US/parks/${id}/rides/${r.id}`});return{parkId:+id,rides}}
export default{async fetch(request){if(request.method==="OPTIONS")return new Response(null,{status:204,headers:cors(request)});if(request.method!=="GET")return json(request,{error:"Method not allowed"},405,0);const u=new URL(request.url);if(u.pathname==="/health")return json(request,{status:"ok",service:"vaca-live-api",time:new Date().toISOString()},200,0);if(u.pathname!=="/api/day")return json(request,{error:"Not found"},404,0);const date=u.searchParams.get("date");if(!/^\d{4}-\d{2}-\d{2}$/.test(date||""))return json(request,{error:"date must use YYYY-MM-DD"},400,0);const ids=[...new Set((u.searchParams.get("parks")||"").split(",").map(x=>x.trim()).filter(x=>ALLOWED_PARKS.has(x)))],[w,ps]=await Promise.all([weather(date).then(value=>({ok:true,value})).catch(error=>({ok:false,error:error.message})),Promise.all(ids.map(async id=>{try{return{ok:true,value:await park(id)}}catch(error){return{ok:false,parkId:+id,error:error.message}}}))]),parks={};for(const x of ps)parks[String(x.ok?x.value.parkId:x.parkId)]=x.ok?x.value:{parkId:x.parkId,rides:[],error:x.error};return json(request,{generatedAt:new Date().toISOString(),weather:w.ok?w.value:{date,daily:null,hourly:[],error:w.error},parks},200,300)}};
